=pod

=encoding UTF-8

=head1 ОПИСАНИЕ

Гостевая книга предоставляет возможность пользователям сайта оставлять сообщения на сайте.

=head1 ТРЕБОВАНИЯ

1. Данные о IP-адресе

2. Браузере,

3. Дате написания сообщения.

4. User Name – обязательное поле

5. E-mail (формат e-mail) - обязательное поле

6. Homepage (формат URL) – необязательное поле

7. Text (непосредственно сам текст сообщения, HTML тэги недопустимы) – обязательное поле

8. Сортировки  (по умолчанию - LIFO)

9. Пагинация    (количество сообщений на странице в конфиге).

10. SQL

11. Config

=head1 ИНСТРУМЕНТЫ

1. Apache (mod_perl или cgi) + Nginx (прокси)

2. PERL5 (POD, Critic) без тестов.

3. MySQL

4. Mojolicious

5. latest (warnings, strict),

6. TT,

7. CRUD with validation,

8. CAPTCHA,

9. DBI,

10. XSS (учтено для всех полей + HTML символы) my $safe = convert_XSS($stuff); # results in '&lt;script&gt;bad stuff&lt;/script&gt;'

=cut
